#!/usr/bin/env bash
# Measure the Rust library's in-memory operations with pilot-bench and print
# a Markdown table.
#
# Usage: ./tests/bench_rust.sh
#
# Columns: operation, mean MiB/s, CI width, runs.  The CI column is the full
# width of the 95% confidence interval, as pilot-bench prints it after
# "Reading CI"; the interval is the mean plus or minus half of it.
#
# Workload: 1 MiB of synthetic data and a copy with about 5% of its bytes
# replaced, generated by the pilot_delta binary; default parameters.
#
# Requirements:
#   - pilot-bench, at $PILOT_BENCH_CLI or ~/pilot-bench/build/cli/bench
#   - pilot_delta, built by:
#       cd src/rust/delta && cargo build --release --bin pilot_delta
set -euo pipefail

BENCH="${PILOT_BENCH_CLI:-$HOME/pilot-bench/build/cli/bench}"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PILOT="$REPO_ROOT/src/rust/delta/target/release/pilot_delta"

measure() {
    local name=$1
    local out mean ci rounds status=0
    out=$("$BENCH" run_program --preset quick \
          --pi "${name},MiB/s,0,1,1" \
          -- "$PILOT" "$name" 2>&1) || status=$?
    if [[ "$status" -ne 0 ]]; then
        echo "pilot-bench failed for $name with status $status:" >&2
        echo "$out" >&2
        exit 1
    fi
    mean=$(echo   "$out" | awk '/Reading mean/{print $5}')
    ci=$(echo     "$out" | awk '/Reading CI/{print $5}')
    rounds=$(echo "$out" | awk '/^Rounds:/{print $2}')
    printf "| %-28s | %10s | %10s | %5s |\n" \
           "$name" "$mean" "$ci" "$rounds"
}

sep() { echo "|------------------------------|------------|------------|-------|"; }

hdr() {
    echo ""
    echo "### $1"
    echo ""
    echo "| Operation                    |   MiB/s    | CI width (95%) | Runs  |"
    sep
}

hdr "Encode (1 MiB, ~5% mutations)"
measure encode_greedy_1m
measure encode_onepass_1m
measure encode_correcting_1m

hdr "Decode / In-place (1 MiB)"
measure decode_1m
measure inplace_1m

echo ""
