#!/usr/bin/env python3
"""Generate static radar SVG charts for ANALYSIS.md.

GitHub's Mermaid parser is inconsistent for radar charts with labels such as
"C++".  These committed SVG assets avoid parser failures and keep rendering
stable across viewers.
"""

from __future__ import annotations

import html
import math
from pathlib import Path


WIDTH = 760
HEIGHT = 640
CX = 300.0
CY = 280.0
RADIUS = 210.0

BG = "#fbfaf6"
GRID = "#d8d2c8"
AXIS = "#8f8779"
TEXT = "#2f2a22"
SUBTEXT = "#5f574d"


def polar(radius: float, angle: float) -> tuple[float, float]:
    return (CX + radius * math.cos(angle), CY + radius * math.sin(angle))


def fmt_points(points: list[tuple[float, float]]) -> str:
    return " ".join(f"{x:.1f},{y:.1f}" for (x, y) in points)


def label_anchor(x: float) -> str:
    if x < CX - 16:
        return "end"
    if x > CX + 16:
        return "start"
    return "middle"


def label_y(y: float) -> float:
    if y < CY - RADIUS + 28:
        return y - 4
    if y > CY + RADIUS - 28:
        return y + 14
    return y + 4


def radar_svg(
    *,
    title: str,
    desc: str,
    labels: list[str],
    series: list[tuple[str, str, float, list[float]]],
    max_value: float,
    ring_labels: list[float],
) -> str:
    n = len(labels)
    angles = [(-math.pi / 2.0) + (2.0 * math.pi * i / n) for i in range(n)]
    rings = [RADIUS * i / len(ring_labels) for i in range(1, len(ring_labels) + 1)]

    out: list[str] = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {WIDTH} {HEIGHT}" role="img" aria-labelledby="title desc">',
        "  <!-- Generated by assets/generate_analysis_radars.py -->",
        f'  <title id="title">{html.escape(title)}</title>',
        f'  <desc id="desc">{html.escape(desc)}</desc>',
        "  <style>",
        f"    .bg {{ fill: {BG}; }}",
        f"    .grid {{ fill: none; stroke: {GRID}; stroke-width: 1; }}",
        f"    .axis {{ stroke: {AXIS}; stroke-width: 1.1; }}",
        f'    .label {{ fill: {TEXT}; font: 13px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}',
        f'    .small {{ fill: {SUBTEXT}; font: 11px ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }}',
        "  </style>",
        f'  <rect class="bg" x="0" y="0" width="{WIDTH}" height="{HEIGHT}" rx="16" />',
        "",
    ]

    for r in rings:
        pts = fmt_points([polar(r, a) for a in angles])
        out.append(f'  <polygon class="grid" points="{pts}" />')

    out.append("")
    for a in angles:
        x, y = polar(RADIUS, a)
        out.append(f'  <line class="axis" x1="{CX:.0f}" y1="{CY:.0f}" x2="{x:.1f}" y2="{y:.1f}" />')

    out.append("")
    for idx, ring_val in enumerate(ring_labels, start=1):
        y = CY - (RADIUS * idx / len(ring_labels))
        txt = f"{ring_val:g}"
        out.append(f'  <text class="small" x="{CX + 16:.1f}" y="{y + 2:.1f}">{txt}</text>')

    out.append("")
    for label, angle in zip(labels, angles):
        x, y = polar(RADIUS + 28, angle)
        anchor = label_anchor(x)
        y_adj = label_y(y)
        out.append(
            f'  <text class="label" x="{x:.1f}" y="{y_adj:.1f}" text-anchor="{anchor}">{html.escape(label)}</text>'
        )

    out.append("")
    for name, color, fill_opacity, values in series:
        points = []
        for val, angle in zip(values, angles):
            rr = RADIUS * max(0.0, min(val, max_value)) / max_value
            points.append(polar(rr, angle))
        out.append(
            f'  <polygon points="{fmt_points(points)}" fill="{color}" fill-opacity="{fill_opacity:.2f}" stroke="{color}" stroke-width="2" />'
        )
        for x, y in points:
            out.append(f'  <circle cx="{x:.1f}" cy="{y:.1f}" r="2.3" fill="{color}" />')

    out.extend(
        [
            "",
            f'  <text class="label" x="20" y="{HEIGHT - 84}">{html.escape(title)}</text>',
            f'  <text class="small" x="20" y="{HEIGHT - 64}">Axes are categorical (languages); polygon edges connect axis values only.</text>',
        ]
    )

    lx = 20
    ly = HEIGHT - 42
    for name, color, _fill_opacity, _values in series:
        out.append(f'  <rect x="{lx}" y="{ly - 11}" width="14" height="14" rx="2" fill="{color}" />')
        out.append(f'  <text class="small" x="{lx + 20}" y="{ly}">{html.escape(name)}</text>')
        lx += 170

    out.append("</svg>")
    return "\n".join(out) + "\n"


def write_chart(
    name: str,
    title: str,
    desc: str,
    labels: list[str],
    series: list[tuple[str, str, float, list[float]]],
    max_value: float,
    ring_labels: list[float],
) -> None:
    output = Path(__file__).with_name(name)
    output.write_text(
        radar_svg(
            title=title,
            desc=desc,
            labels=labels,
            series=series,
            max_value=max_value,
            ring_labels=ring_labels,
        ),
        encoding="utf-8",
    )


def main() -> None:
    write_chart(
        "kernel-onepass-speed-radar.svg",
        "Onepass speed score (faster is larger, max=100) - linux-5.1 -> 5.1.1",
        "Kernel onepass speed score by language. Scores normalize encode time to the fastest implementation.",
        ["C", "Go", "C++", "Java", "Rust"],
        [("Speed score", "#0f766e", 0.22, [100.0, 93.3, 87.5, 77.8, 70.0])],
        100.0,
        [20, 40, 60, 80, 100],
    )
    write_chart(
        "kernel-correcting-speed-radar.svg",
        "Correcting speed score (faster is larger, max=100) - linux-5.1 -> 5.1.1",
        "Kernel correcting speed score by language. Scores normalize encode time to the fastest implementation.",
        ["Rust", "Java", "C++", "Go", "C"],
        [("Speed score", "#8b5cf6", 0.22, [100.0, 94.7, 85.5, 59.7, 57.3])],
        100.0,
        [20, 40, 60, 80, 100],
    )
    write_chart(
        "shakespeare-onepass-throughput-radar.svg",
        "Onepass throughput profile (MiB/s) - Shakespeare, dyson M4 Pro, 2026-10-03",
        "Onepass throughput by language for Shakespeare pilot-bench workload on dyson M4 Pro.",
        ["Rust", "Go", "C", "C++", "Java"],
        [("Throughput", "#0f766e", 0.22, [62.26, 61.02, 50.58, 47.15, 28.97])],
        75.0,
        [15, 30, 45, 60, 75],
    )
    write_chart(
        "shakespeare-correcting-throughput-radar.svg",
        "Correcting throughput profile (MiB/s) - Shakespeare, dyson M4 Pro, 2026-10-03",
        "Correcting throughput by language for Shakespeare pilot-bench workload on dyson M4 Pro.",
        ["Rust", "C++", "Go", "C", "Java"],
        [("Throughput", "#2563eb", 0.22, [69.29, 56.49, 41.40, 39.41, 29.18])],
        75.0,
        [15, 30, 45, 60, 75],
    )
    write_chart(
        "shakespeare-onepass-multimachine-radar.svg",
        "Onepass throughput by machine (MiB/s) - Shakespeare",
        "Onepass throughput by language on dyson M4 Pro, dmz i5-8259U and baase Cortex-X925, 2026-10-03, Pilot a6e6e77.",
        ["Rust", "Go", "C", "C++", "Java"],
        [
            ("dyson M4 Pro", "#0f766e", 0.18, [62.26, 61.02, 50.58, 47.15, 28.97]),
            ("dmz i5", "#1d4ed8", 0.14, [17.72, 13.55, 17.00, 18.92, 10.31]),
            ("baase X925", "#be123c", 0.14, [36.90, 28.21, 28.48, 34.41, 20.81]),
        ],
        75.0,
        [15, 30, 45, 60, 75],
    )
    write_chart(
        "shakespeare-correcting-multimachine-radar.svg",
        "Correcting throughput by machine (MiB/s) - Shakespeare",
        "Correcting throughput by language on dyson M4 Pro, dmz i5-8259U and baase Cortex-X925, 2026-10-03, Pilot a6e6e77.",
        ["Rust", "Go", "C", "C++", "Java"],
        [
            ("dyson M4 Pro", "#2563eb", 0.18, [69.29, 41.40, 39.41, 56.49, 29.18]),
            ("dmz i5", "#0f766e", 0.14, [17.87, 13.53, 14.81, 16.12, 9.22]),
            ("baase X925", "#be123c", 0.14, [42.04, 30.97, 43.42, 41.73, 23.49]),
        ],
        75.0,
        [15, 30, 45, 60, 75],
    )


if __name__ == "__main__":
    main()
